coverage:
  status:
    project:
      default:
        target: auto
      api-client:
        flags:
          - api-client
      app:
        flags:
          - app

flags:
  api-client:
    carryforward: true
    paths:
      - api-client
  app:
    carryforward: true
    paths:
      - app
