version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: monthly
      time: "23:30"
    open-pull-requests-limit: 20
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "23:30"
    open-pull-requests-limit: 10
