name: Build Noice Full APK

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-full-apk:
    name: Build Full Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Full APK
        run: ./gradlew assembleFullDebug

      - name: Upload Full APK
        uses: actions/upload-artifact@v4
        with:
          name: noice-full-debug
          path: app/build/outputs/apk/full/debug/*.apk
